name: Docker Build And Publish

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      AWS_ROLE_TO_ASSUME:
        required: true
        type: string
      ECR_URI:
        required: true
        type: string
      TAG_REF:
        required: true
        type: string

# permission can be added at job level or workflow level    
permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-template:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t norns-weather-service:$TAG_REF .

      - name: Publish to AWS ECR
        run: |
          docker push ${{ ECR_URI }}:${{ TAG_REF }}