name: Docker Build And Publish
on:
  release:
    types: 
      - published
env:
  AWS_REGION : "eu-central-1"
  DEV_SUFFIX : "development"
  STAG_SUFFIX : "staging"
  PROD_SUFFIX : "production"

  ECR_DEV: "360532638835.dkr.ecr.eu-central-1.amazonaws.com/ever-given-development/norns-weather-service"
  
# permission can be added at job level or workflow level    
permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-template:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::360532638835:role/github-norns
          aws-region: ${{ env.AWS_REGION }}

      - name: Set tag as env var
        run: |
          TAG_REF="${{ github.ref }}"
          echo "TAG_REF=$TAG_REF" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t norns-weather-service:$TAG_REF .

      - name: Publish to AWS ECR
        run: |
          docker push $ECR_URI:$TAG_REF