name: Build and publish static files to S3

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      AWS_ROLE_TO_ASSUME:
        required: true
        type: string
      S3_URI:
        required: true
        type: string

# permission can be added at job level or workflow level    
permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-template:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set tag as env var
        run: echo "TAG_REF=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Build Step
        run: |
          npm install
          npm run build

      - name: Publish to S3
        run: |
          aws s3 sync build/ ${{ inputs.S3_URI }} --delete